# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hoofbeats Health
email: HoofbeatsHealth@gmail.com
description: a digital toolbox for managing your healthcare
baseurl: "hoofbeats"
url: "https://hoofbeats.github.io"
repository: hoofbeats.github.io

twitter_username: HoofbeatsHealth
github_username:  Hoofbeats
fb_id: 333599240332696
google_analytics: UA-76343771-1
google_site_verification: UA-76343771-1
ga_username: UA-76343771-1
prime-trial-banner: "amp/_store/_prime_trial_320x50.html"

# Build settings
markdown: kramdown
permalink: /:title/
excerpt_separator: <!-- excerpt -->
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
